python_crash_course/project_3_web_app/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

python_crash_course/project_3_web_app/learning_logs/urls.py
"""
Defines URL patterns for learning_logs application
learning_logs/urls.py
"""
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('update_entry/<int:entry_id>/', views.update_entry, name='update_entry'),
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),
    ]

python_crash_course/project_3_web_app/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
        path('', include('django.contrib.auth.urls')),
        path('register/', views.register, name='register'),
        ]

python_crash_course/project_3_web_app/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."

python_crash_course/project_3_web_app/learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

python_crash_course/project_3_web_app/learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
   topics = Topic.objects.filter(owner=request.user).order_by('date_added')
   context = {'topics': topics}
   return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    if request.method != 'POST':    # if 'GET'
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':    # if 'GET'
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def update_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':    # if 'GET'
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/update_entry.html', context)

@login_required
def delete_entry(request, entry_id):
    try:
        entry = Entry.objects.get(id=entry_id)
        topic = Topic.objects.get(id=entry.topic.id)
        entries = topic.entry_set.order_by('-date_added')
    except Entry.DoesNotExist:
        return redirect('learning_logs:index')
    entry.delete()
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

python_crash_course/project_3_web_app/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

python_crash_course/project_3_web_app/learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>
	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  </head>

  <body>
	<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
	  <div class="container-fluid">
		<a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
		  <ul class="navbar-nav mr-auto">
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topic</a>
			</li>
		  </ul>
		  <ul class="navbar-nav ml-auto">
			{% if user.is_authenticated %}
			<li class="nav-item">
				<span class="navbar-text">Hello, {{ user.username }}.</span>
			</li>  
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
			</li>  
			{% else %}
			<li class="nav-item">
			  <form>
				<button type="submit" formaction="{% url 'users:login' %}" 
				  class="btn btn-outline-success btn-sm">Login</button>
				<button type="submit" formaction="{% url 'users:register' %}" 
				  class="btn btn-outline-success btn-sm">Register</button>
			  </form>
			</li>  
			{% endif %}
		  </ul>
		</div>
	  </div>
	</nav>
  </body>
</html>
    
{% block content %}{% endblock content %}

python_crash_course/project_3_web_app/learning_logs/templates/learning_logs/footer.html
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item">
		  <a href="{% url 'learning_logs:index' %}" class="nav-link px-2 text-muted">
			  Home
		  </a>
	  </li>
      <li class="nav-item">
		  <a href="{% url 'learning_logs:topics' %}" class="nav-link px-2 text-muted">
			  Topics
		  </a>
	  </li>
      <li class="nav-item">
		  <a href="http://localhost/phpmyadmin/index.php?route=/database/structure&server=1&db=learning_log" target="_blank" class="nav-link px-2 text-muted">
			  phpMyAdmin
		  </a>
	  </li>
      <li class="nav-item">
		  <a href="https://getbootstrap.com/docs/5.1/getting-started/introduction/" target="_blank" class="nav-link px-2 text-muted">
			  Bootstrap
		  </a>
	  </li>
      <li class="nav-item">
		  <a href="https://docs.djangoproject.com/en/3.2/" target="_blank" class="nav-link px-2 text-muted">
			  FAQs
		  </a>
	  </li>
      <li class="nav-item">
		  <a href="http://nook17.pl/about" target="_blank" class="nav-link px-2 text-muted">
			  About
		  </a>
	  </li>
    </ul>
    <p class="text-center text-muted">&copy; 2021 - Nook Web Developer</p>
  </footer>
</div>

python_crash_course/project_3_web_app/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
	<main class="container">
	  <div class="bg-light p-5 rounded">
		<h1>Track your learning</h1>
		<p class="lead">Make your own Learning Log, and keep a list of the topics you're learning about. Whenever you learn something new about a topic, make an entry summarizing what you've learned.</p>
	  </div>
	</main>


  {% include "learning_logs/footer.html" %}
{% endblock content %}

python_crash_course/project_3_web_app/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% load bootstrap %}

{% block content %}
<p class="text-center">New entry for {{ topic }}</p>
<div class="container">
	<form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
	  <div class="mb-3">
		<label for="InputTopic" class="form-label">Entry</label>
		{% csrf_token %}
		{{ form.as_p }}
		<div id="topicHelp" class="form-text">Enter you new entry</div>
	  </div>
	  <button type="submit" class="btn btn-primary">Send</button>
	</form>
</div>


  {% include "learning_logs/footer.html" %}
{% endblock content %}

python_crash_course/project_3_web_app/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% load bootstrap %}

{% block content %}
<p class="text-center">New topic</p>
<div class="container">
	<form action="{% url 'learning_logs:new_topic' %}" method="post">
	  <div class="mb-3">
		<label for="InputTopic" class="form-label">Topic</label>
		{% csrf_token %}
		{{ form|bootstrap }}
		<div id="topicHelp" class="form-text">Enter you new topic</div>
	  </div>
	  <button type="submit" class="btn btn-primary">Send</button>
	</form>
</div>


  {% include "learning_logs/footer.html" %}
{% endblock content %}

python_crash_course/project_3_web_app/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
<p class="text-center">Topic: {{ topic  }}</p>
	<ul class="list-group">
	  {% for entry in entries %}
	    <li class="list-group-item">
			<p>{{ entry.date_added|date:'d M Y H:i' }} 
			  <a href="{% url 'learning_logs:update_entry' entry.id %}">
				  <i class="bi bi-pen text-info" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit"></i></a>
			  <a href="{% url 'learning_logs:delete_entry' entry.id %}">
				  <i class="bi bi-trash text-danger" data-bs-toggle="tooltip" data-bs-placement="top" title="Delete"></i></a>
			</p>
			<p>{{ entry.text|linebreaks }}</p>
		</li>
      {% empty %}
		<li class="list-group-item">No added any entires</li>
	 {% endfor %}
	</ul>
	<div class='text-center'>
	  <form>
		<button type="submit" formaction="{% url 'learning_logs:new_entry' topic.id %}" 
		  class="btn btn-outline-dark btn-sm">Add entry</button>
  	  </form>
	</div>
  {% include "learning_logs/footer.html" %}
{% endblock content %}

python_crash_course/project_3_web_app/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}
<div class='container'>  
  <p class="text-center">Topics List</p>
	<ul class="list-group list-group-flush">
	  {% for topic in topics %}
	    <li class="list-group-item">
		  <a href="{% url 'learning_logs:topic' topic.id %}">
			{{ topic  }}
		  </a>
		</li>
      {% empty %}
		<li class="list-group-item">No added any topic</li>
	 {% endfor %}
	</ul>
	<div class='text-center'>
	  <form>
		<button type="submit" formaction="{% url 'learning_logs:new_topic' %}" 
		  class="btn btn-outline-dark btn-sm">Add topic</button>
  	  </form>
	</div>
</div>
  {% include "learning_logs/footer.html" %}
{% endblock content %}

python_crash_course/project_3_web_app/learning_logs/templates/learning_logs/update_entry.html
{% extends "learning_logs/base.html" %}

{% load bootstrap %}

{% block content %}
<p class="text-center">Update entry for {{ topic }}</p>
<div class="container">
	<form action="{% url 'learning_logs:update_entry' entry.id %}" method="post">
	  <div class="mb-3">
		<label for="InputTopic" class="form-label">Old entry</label>
		{% csrf_token %}
		{{ form.as_p }}
		<div id="topicHelp" class="form-text">Edit entry for topic</div>
	  </div>
	  <button type="submit" class="btn btn-primary">Update</button>
	</form>
</div>


  {% include "learning_logs/footer.html" %}
{% endblock content %}