django/04_statement/ver_1.1/cfd/urls.py
from django.urls import path
from . import views

app_name = 'cfd'
urlpatterns = [
    path('', views.index, name='index'),
    path('api', views.ChartData.as_view()),
    path('statement/', views.statement, name='statement'),
    path('new_statement/', views.new_statement, name='new_statement'),
    path('statement/<str:url_statement>/', views.statements, name='statements'),
    path('delete_statement/<int:ticket_id>/<str:url_statement>/', views.delete_statement, name='delete_statement'),
    path('deposit/', views.deposit, name='deposit'),
    path('new_deposit/', views.new_deposit, name='new_deposit'),
    path('update_deposit/<int:deposit_id>/', views.update_deposit, name='update_deposit'),
    path('delete_deposit/<int:deposit_id>/', views.delete_deposit, name='delete_deposit'),
    path('withdrawal/', views.withdrawal, name='withdrawal'),
    path('new_withdrawal/', views.new_withdrawal, name='new_withdrawal'),
    path('update_withdrawal/<int:withdrawal_id>/', views.update_withdrawal, name='update_withdrawal'),
    path('delete_withdrawal/<int:withdrawal_id>/', views.delete_withdrawal, name='delete_withdrawal'),
    path('year/', views.year, name='year'),
    path('year/set/', views.new_percent, name='new_percent'),
    path('calc/', views.calc, name='calc'),
    path('calc/set/', views.calc_set, name='calc_set'),
    path('calc/buy_create/', views.calc_buy_create, name='calc_buy_create'),
    path('calc/buy_delete/<int:buy_id>/', views.calc_buy_delete, name='calc_buy_delete'),
    path('quarter/', views.quarter, name='quarter'),
    path('quarter/set/', views.quarter_set, name='quarter_set'),
    path('quarter/set_percent/', views.quarter_set_percent, name='quarter_set_percent'),
    path('pipmargin/', views.pipmargin, name='pipmargin'),
    path('pipmargin/set/', views.pipmargin_set, name='pipmargin_set'),
    path('daily/', views.daily, name='daily'),
    path('point/', views.point, name='point'),
    path('point/set/', views.point_set, name='point_set'),
    ]

django/04_statement/ver_1.1/cfd/templates/cfd/base.html
{% load bootstrap4 %}
{% load static %}

<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Statement</title>
	<link rel="icon" type="image/png" sizes="96x96"
	  href="{% static 'cfd/assets/logo_nook.png' %}">
	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}
	<link rel="stylesheet" 
	  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
	<link rel="stylesheet" href="{% static 'cfd/style/style.css' %}">
{% block link %}{% endblock link %}
  </head>

  <body>
	<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
	  <div class="container-fluid">
		<a class="navbar-brand" href="{% url 'cfd:index' %}">
			<img src="{% static 'cfd/assets/logo_nook.png' %}" alt="" 
			width="30" height="24" class="d-inline-block align-text-top">
			Statement
		</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
			data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" 
			aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
		  <ul class="navbar-nav mr-auto">
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'cfd:deposit' %}">Deposit</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'cfd:withdrawal' %}">Withdrawal</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'cfd:statement' %}">Statement</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'cfd:quarter' %}">Quarter</a>
			</li>

			<li class="nav-item dropdown">
			  <a class="nav-link dropdown-toggle" href="#"
				  id="navbarDropdown" role="button" data-bs-toggle="dropdown"
				  aria-expanded="false">
				Calculator
			  </a>
			  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
				<li><a class="dropdown-item" href="{% url 'cfd:calc' %}">
						Take Profit</a></li>
				<li><a class="dropdown-item" href="{% url 'cfd:pipmargin' %}">Margin & Pip Value</a></li>
				<li><a class="dropdown-item" href="{% url 'cfd:daily' %}">Daily Calculations</a></li>
				<li><a class="dropdown-item" href="{% url 'cfd:point' %}">Daily Point</a></li>
			  </ul>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'cfd:year' %}">Year</a>
			</li>
		  </ul>

		  <ul class="navbar-nav ml-auto">
			{% if user.is_authenticated %}
			<li class="nav-item">
				<span class="navbar-text">Hello, {{ user.username }}.</span>
			</li>  
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
			</li>  
			{% else %}
			<li class="nav-item">
			  <form>
				<button type="submit" formaction="{% url 'users:login' %}" 
				  class="btn btn-outline-success btn-sm">Login</button>
				<button type="submit" formaction="{% url 'users:register' %}" 
				  class="btn btn-outline-success btn-sm">Register</button>
			  </form>
			</li>  
			{% endif %}
		  </ul>

		</div>
	  </div>
	</nav>
{% block content %}{% endblock content %}
	<!-- Bootstrap Date-Picker Plugin -->
	<script 
	src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" 
	integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" 
	crossorigin="anonymous">
	</script>
	<script type="text/javascript" 
	src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js">
	</script>
	<link rel="stylesheet" 
	href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
  </body>
</html>

django/04_statement/ver_1.1/cfd/templates/cfd/footer.html
{% load static %}
{% block link %}
	<link rel="stylesheet" href="{% static 'cfd/style/footer.css' %}" type="text/css">
{% endblock link %}
	<footer class="footer mt-auto py-3 ">
	  <div class="container">
		<ul class="nav justify-content-center border-bottom ">
		  <li class="nav-item">
			  <a href="{% url 'cfd:index' %}" class="nav-link px-2 text-muted">
				  Home
			  </a>
		  </li>
		  <li class="nav-item">
			  <a href="{% url 'cfd:deposit' %}" class="nav-link px-2 text-muted">
				  Deposit
			  </a>
		  </li>
		  <li class="nav-item">
			  <a href="{% url 'cfd:withdrawal' %}" class="nav-link px-2 text-muted">
				  Withdrawal
			  </a>
		  </li>
		  <li class="nav-item">
			  <a href="{% url 'cfd:statement' %}" class="nav-link px-2 text-muted">
				  Statement
			  </a>
		  </li>
		  <li class="nav-item">
			  <a href="{% url 'cfd:quarter' %}" class="nav-link px-3 text-muted">
				  Quarter
			  </a>
		  </li>
		  <li class="nav-item dropup">
		    <a class="nav-link dropdown-toggle text-muted" href="#"
				data-bs-toggle="dropdown" aria-expanded="false">Calculator</a>
			<ul class="dropdown-menu" aria-labelledby="dropdown10">
			  <li><a class="dropdown-item" href="{% url 'cfd:calc' %}">
					  Take Profit</a></li>
			  <li><a class="dropdown-item" href="{% url 'cfd:pipmargin' %}">
					  Margin & Pip Value</a></li>
			  <li><a class="dropdown-item" href="{% url 'cfd:daily' %}">
					  Daily Calculations</a></li>
			  <li><a class="dropdown-item" href="{% url 'cfd:point' %}">
					  Daily Point</a></li>
			</ul>
		  </li>
		  <li class="nav-item">
			  <a href="{% url 'cfd:year' %}" class="nav-link px-2 text-muted">
				  Year
			  </a>
		  </li>
		  <li class="nav-item">
			  <a href="http://localhost/phpmyadmin/index.php" 
				  target="_blank" class="nav-link px-2 text-muted">
				  phpMyAdmin
			  </a>
		  </li>
		  <li class="nav-item">
			  <a href="https://getbootstrap.com/docs/5.1/"
				  target="_blank" class="nav-link px-2 text-muted">
				  Bootstrap
			  </a>
		  </li>
		  <li class="nav-item">
			  <a href="https://docs.djangoproject.com/en/3.2/"
				  target="_blank" class="nav-link px-2 text-muted">
				  FAQs
			  </a>
		  </li>
		  <li class="nav-item">
			<a href="#" data-bs-toggle="modal" data-bs-target="#Modal"
				class="nav-link px-2 text-muted">About</a>
		  </li>
		</ul>
		<p class="text-center text-muted">&copy; 2021 - Nook Web Developer</p>
	  </div>
	</footer>

<!-- Modal -->
<div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="ModalLabel" 
	aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="nmodal-content shadow mb-5 bg-body rounded">
      <div class="nmodal-header">
		<img class="nookico" alt="nook icon" 
		  src="{% static 'cfd/assets/logo_nook.png' %}">
		  <div class="ml-3">
			<h4 class="modal-title" id="ModalLabel">Statement</h4>
			<p class="">Version 1.1</p>
		  </div>
      </div>
      <div class="modal-body">
		<div class="panel-group" id="accordion" role="tablist"
			aria-multiselectable="true">
		<p class="lead">Release:</p>

		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="headingOne">
			  <h5 class="panel-title">
				<a role="button" data-toggle="collapse" class="nlink" 
					data-parent="#accordion" href="#collapseOne" 
					aria-expanded="true" aria-controls="collapseOne">
				  Version 1.0
				</a>
			  </h5>
			</div>
			<div id="collapseOne" class="panel-collapse collapse in" 
				role="tabpanel" aria-labelledby="headingOne">
			  <div class="panel-body">
				The basic functionality of the 'Statement Application' deploy to the production server 
			  </div>
			</div>
		  </div> <!-- Panel -->

		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="headingTwo">
			  <h5 class="panel-title">
				<a class="collapsed nlink" role="button" data-toggle="collapse"
					data-parent="#accordion" href="#collapseTwo" 
					aria-expanded="false" aria-controls="collapseTwo">
					Version 1.1
				</a>
			  </h5>
			</div>
			<div id="collapseTwo" class="panel-collapse collapse" 
				role="tabpanel"	aria-labelledby="headingTwo">
			  <div class="panel-body">
				Major changes:
				<ul>
					<li>added second chart 'return by trade' on index site</li>
					<li>highlighted all trades finished 'take profit' or 'stop loss'</li>
					<li>possibility to delete the single statement from the database</li>
					<li>added site about in modal window</li>
					<li>The ability to upload a statement of files to databases</li>
				</ul>
			  </div>
			</div>
		  </div> <!-- Panel -->

		</div> <!-- accordion -->
	  </div> <!-- modal-body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary btn-sm" 
			data-bs-dismiss="modal">Close
		</button>
	  </div> <!-- modal-footer -->
    </div>
  </div>
</div>

django/04_statement/ver_1.1/cfd/templates/cfd/statement.html
{% extends "cfd/base.html" %}
{% load static %}
{% block link %}
	<link rel="stylesheet" href="{% static 'cfd/style/stat_choose_file.css' %}" type="text/css">
{% endblock link %}
{% block content %}
  <main class="container flex-shrink-0">
    <div class="p-5 rounded">
	  <p class="lead">Statement</p>
      <div class="row">
        <div class="col-lg-7 col-md-12 mt-2">
		  <table class="table table-striped">
			  <thead>
				<tr>
				  <th scope="col">Date</th>
				  <th scope="col">Profit</th>
				  <th scope="col">Loss</th>
				  <th scope="col">Balance</th>
				  <th scope="col">Wallet</th>
				</tr>
			  </thead>
			  <tbody>
				{% for dic_date, dic_items in dicts.items %}
				<tr>
				  <td><a href="{% url 'cfd:statements' dic_date %}">{{ dic_items.0 }}</a></td>
				  <td>{{ dic_items.1|floatformat:2 }}</td>
				  <td>{{ dic_items.2|floatformat:2 }}</td>
				  <td>{{ dic_items.3|floatformat:2 }}</td>
				  <td>{{ dic_items.4|floatformat:2 }}</td>
				</tr>
				{% endfor %}
			  </tbody>
		  </table>
		</div> <!-- col -->
		<div class="col-lg-5 col-md-12 mt-2">
			<table class="table table-striped">
			  <thead>
				<tr>
				  <th scope="col">Profit</th>
				  <th scope="col">Loss</th>
				  <th scope="col">Ballance</th>
				  <th scope="col">Commission</th>
				  <th scope="col">Swap</th>
				</tr>
			  </thead>
			  <tbody>
				<tr>
				  <td>{{ profit_sum }}</td>
				  <td>{{ loss_sum }}</td>
				  <td>{{ ballance_sum }}</td>
				  <td>{{ commission_sum }}</td>
				  <td>{{ swap_sum }}</td>
				</tr>
			  </tbody>
			</table>
			<div class="mt-4">
			  <form action="{% url 'cfd:new_statement' %}" method="post">
				{% csrf_token %}
				  <div class="mb-3">
					<label for="formFileSm" class="form-label">
						Upload an Excel file with your daily statement</label>
					<input class="form-control nform-control-sm" id="formFileSm" type="file">
				  </div>						
				  <div class="col-auto text-center">
					<button type="submit" 
						class="btn btn-outline-dark btn-sm">Send
					</button>
				  </div>					
			  </form>
			</div>
		</div> <!-- col -->
      </div> <!-- row -->
    </div>
	</main>
  {% include "cfd/footer.html" %}
{% endblock content %}

django/04_statement/ver_1.1/cfd/templates/cfd/statements.html
{% extends "cfd/base.html" %}
{% load static %}
{% block link %}
	<link rel="stylesheet" href="{% static 'cfd/style/statement.css' %}" type="text/css">
{% endblock link %}

{% block content %}
	<main class="container flex-shrink-0">
		<div class="row">
			<div class="col-md-12">
			  <div class="p-2 rounded">
				<p class="lead">Statement</p>
				  <p>Day: <b>{{ format_day }}</b>*</p>
			  </div>

				<table class="table table-sm">
				  <thead>
					<tr>
					  <th scope="col">Open Time</th>
					  <th scope="col">Type</th>
					  <th scope="col">Size</th>
					  <th scope="col">Item</th>
					  <th scope="col">Open Price</th>
					  <th scope="col">Stop Loss</th>
					  <th scope="col">Take Profit</th>
					  <th scope="col">Close Price</th>
					  <th scope="col">Commission</th>
					  <th scope="col">Swap</th>
					  <th scope="col">Profit</th>
					</tr>
				  </thead>
				  <tbody>
					{% for i, day in day_st.iterrows %}
					<tr>
					  <td>{{ day.1 }}</td> <!-- Open Time -->
					  <td>{{ day.2 }}</td> <!-- Type -->
					  <td>{{ day.3 }}</td> <!-- Size -->
					  <td>{{ day.4 }}</td> <!-- Item -->
					  <td>{{ day.5 }}</td> <!-- Open Price -->
					  {% if day.6 == day.9 %}
					  	  <td class="slcolor">{{ day.6 }}</td> <!-- Stop Loss -->
					  {% else %}
					  	  <td>{{ day.6 }}</td> <!-- Stop Loss -->
					  {% endif %}
					  {% if day.7 == day.9 %}
						  <td class="tpcolor">{{ day.7 }}</td> <!-- Take Profit -->
					  {% else %}
						  <td>{{ day.7 }}</td> <!-- Take Profit -->
					  {% endif %}
					  <td>{{ day.9 }}</td> <!-- Close Price -->
					  <td>{{ day.10 }}</td> <!-- Commission -->
					  <td>{{ day.11 }}</td> <!-- Swap -->
					  <td>{{ day.12 }}</td> <!-- Profit -->
					  <td>
						  <a href="{% url 'cfd:delete_statement' day.0 url_statement %}">
							  <i class="bi bi-trash text-danger ml-4" 
								  data-bs-toggle="tooltip" 
								  data-bs-placement="top" title="Delete"></i>
						  </a>
					  </td>
					</tr>
					{% endfor %}
				  </tbody>
				</table>

			</div> <!-- col -->
		</div> <!-- row -->
		<div class="row">
			<div class="col-md-12">
				<table class="table table-striped">
				  <thead>
					<tr >
					  <th class="text-secondary">Profit</th>
					  <th class="text-secondary">Loss</th>
					  <th class="text-secondary">Balance</th>
					  <th class="text-secondary">pkt</th>
					  <th class="text-secondary">Commission</th>
					  <th class="text-secondary">Swap</th>
					</tr>
				  </thead>
				  <tbody>
					<tr>
					  <td>{{ sum_profit }}</td>
					  <td>{{ loss_profit }}</td>
					  <td>{{ day_sum }}</td>
					  <td>{{ pkt_sum }}</td>
					  <td>{{ commission_sum }}</td>
					  <td>{{ swap_sum }}</td>
					</tr>
				  </tbody>
				</table>
			</div> <!-- col -->
		</div> <!-- row -->

		<div class="row">
			<div class="col-md-2"></div>
				<div class="col-md-8">
					<canvas id="myChart"></canvas>
				</div> <!-- col -->
			<div class="col-md-2"></div>
		</div> <!-- row -->

		<div class="row">
			<div class="col-md-12">
			  <div class="p-2 rounded">
				  <p>* - Close Time</p>
			  </div>
		</div> <!-- row -->
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: {{chartx}},
        datasets: [{
            label: '{{format_day}}',
            data: {{charty}},
            backgroundColor: 'rgba(54, 162, 235, 0.2)',
            borderColor: 'rgba(54, 162, 235, 1)',
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});
</script>



	</main>
  {% include "cfd/footer.html" %}
{% endblock content %}