django/04_statement/ver_1.2/cfd/urls.py
from django.urls import path
from . import views

app_name = 'cfd'
urlpatterns = [
    path('', views.index, name='index'),
    path('api', views.ChartData.as_view()),
    path('statement/', views.statement, name='statement'),
    path('new_statement/', views.new_statement, name='new_statement'),
    path('statement/<str:url_statement>/', views.statements, name='statements'),
    path('delete_statement/<int:ticket_id>/<str:url_statement>/', views.delete_statement, name='delete_statement'),
    path('deposit/', views.deposit, name='deposit'),
    path('new_deposit/', views.new_deposit, name='new_deposit'),
    path('update_deposit/<int:deposit_id>/', views.update_deposit, name='update_deposit'),
    path('delete_deposit/<int:deposit_id>/', views.delete_deposit, name='delete_deposit'),
    path('withdrawal/', views.withdrawal, name='withdrawal'),
    path('new_withdrawal/', views.new_withdrawal, name='new_withdrawal'),
    path('update_withdrawal/<int:withdrawal_id>/', views.update_withdrawal, name='update_withdrawal'),
    path('delete_withdrawal/<int:withdrawal_id>/', views.delete_withdrawal, name='delete_withdrawal'),
    path('year/', views.year, name='year'),
    path('year/set/', views.new_percent, name='new_percent'),
    path('strategy/', views.strategy, name='strategy'),
    path('strategy/set/<int:id>/', views.strategy_set, name='strategy_set'),
    path('calc/', views.calc, name='calc'),
    path('calc/set/', views.calc_set, name='calc_set'),
    path('calc/buy_create/', views.calc_buy_create, name='calc_buy_create'),
    path('calc/buy_delete/<int:buy_id>/', views.calc_buy_delete, name='calc_buy_delete'),
    path('quarter/', views.quarter, name='quarter'),
    path('quarter/set/', views.quarter_set, name='quarter_set'),
    path('quarter/set_percent/', views.quarter_set_percent, name='quarter_set_percent'),
    path('pipmargin/', views.pipmargin, name='pipmargin'),
    path('pipmargin/set/', views.pipmargin_set, name='pipmargin_set'),
    path('daily/', views.daily, name='daily'),
    path('point/', views.point, name='point'),
    path('point/set/', views.point_set, name='point_set'),
    ]

django/04_statement/ver_1.2/statement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('cfd.urls')),
]

django/04_statement/ver_1.2/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
        path('', include('django.contrib.auth.urls')),
        path('register/', views.register, name='register'),
]

django/04_statement/ver_1.2/cfd/forms.py
# import form class from django
from django import forms
# import GeeksModel from models.py
from .models import Deposit, Withdrawal, Notesdb, Strategy, Buy_calc, Quarter, Pipmargin


# create a ModelForm
class DepositForm(forms.ModelForm):
    # specify the name of model to use
    class Meta:
        model = Deposit
        fields = "__all__"


# create a ModelForm
class WithdrawalForm(forms.ModelForm):
    # specify the name of model to use
    class Meta:
        model = Withdrawal
        fields = "__all__"


class NotesdbForm(forms.ModelForm):
    class Meta:
        model = Notesdb
        fields = "__all__"
        # widgets = {
        #     'buy_or_sell': forms.RadioSelect
        # }


class StrategyForm(forms.ModelForm):
    class Meta:
        model = Strategy
        fields = "__all__"
        # abstract = True


class Buy_calcForm(forms.ModelForm):
    class Meta:
        model = Buy_calc
        fields = "__all__"


class QuarterForm(forms.ModelForm):
    class Meta:
        model = Quarter
        fields = "__all__"


class PipmarginForm(forms.ModelForm):
    class Meta:
        model = Pipmargin
        fields = "__all__"

django/04_statement/ver_1.2/cfd/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import Statement, Deposit, Withdrawal, Notesdb, Strategy, Buy_calc, Quarter, Pipmargin
from .forms import DepositForm, WithdrawalForm, NotesdbForm, StrategyForm, Buy_calcForm, QuarterForm, PipmarginForm
import pandas as pd
import json, time
from datetime import datetime
from sqlalchemy import create_engine


def df_db():
    statements = Statement.objects.all().values()
    df = pd.DataFrame(statements)
    return df

def stat_db():
    statement = Statement.objects.all().values()
    return statement


def depo_db():
    deposits = Deposit.objects.all().values().order_by('date_dep')
    return deposits


def depo_db_pandas():
    deposits = Deposit.objects.all().values()
    depo = pd.DataFrame(deposits)
    return depo


def wd_db():
    withdrawal = Withdrawal.objects.all().values().order_by('date_wd')
    return withdrawal


def wd_db_pandas():
    withdrawal = Withdrawal.objects.all().values()
    wd = pd.DataFrame(withdrawal)
    return wd


def pipmargin_db_pandas():
    pipmarg = Pipmargin.objects.all().values()
    pm = pd.DataFrame(pipmarg)
    return pm


def deposit_sum():
    depo_sum = depo_db_pandas()
    if not depo_sum.empty:
        deposit_sum = depo_sum.amount_dep.sum()
    else:
        deposit_sum = 0
    return deposit_sum


def withdrawal_sum():
    wd_sum = wd_db_pandas()
    if not wd_sum.empty:
        withdrawal_sum = wd_sum.amount_wd.sum()
    else:
        withdrawal_sum = 0
    return withdrawal_sum


def wallet():
    df = df_db()
    commission_sum = df.commission.sum()
    swap_sum = df.swap.sum()
    filter_profit = (df['profit'] > 0)
    filter_loss = (df['profit'] < 0)
    profit = df.loc[filter_profit, 'profit'].sum()
    loss_sum = df.loc[filter_loss, 'profit'].sum()
    profit_sum = profit + loss_sum + commission_sum + swap_sum
    wall = profit_sum + deposit_sum()
    return wall


def days_count():
    df = df_db()
    return df['close_time'].dt.date.nunique()


def transactions():
    df = df_db()
    return df.shape[0]


def f_stat():
    df = df_db()
    depo_sum = deposit_sum()
    commission_sum = df.commission.sum()
    swap_sum = df.swap.sum()
    filter_profit = (df['profit'] > 0)
    filter_loss = (df['profit'] < 0)
    profit_sum = df.loc[filter_profit, 'profit'].sum()
    loss_sum = df.loc[filter_loss, 'profit'].sum()
    ballance_sum = profit_sum + loss_sum + commission_sum + swap_sum
    df['open_time'] = pd.to_datetime(df['open_time']).dt.date
    df['close_time'] = pd.to_datetime(df['close_time']).dt.date
    url_statements = list(set(df['close_time']))
    url_statements.sort()
    format_days, profit_per_day, loss_per_day, balance_per_day = [], [], [], [] 
    swap_day, wallet = [], []
    for url_stat in url_statements:
        day_st = df.loc[df['close_time'] == url_stat]
        format_days.append(url_stat.strftime('%A - %d %B %Y'))
        # --- commision ---
        commission_day = day_st.commission.sum()
        swap_day.append(day_st.swap.sum())
        # --- Profit ----
        sum_profit = 0
        for i in day_st.profit:
            if i > 0:
                sum_profit += i
        profit_per_day.append(sum_profit + commission_day)
        # --- Loss ---
        loss_profit = 0
        for i in day_st.profit:
            if i < 0:
                loss_profit += i
        loss_per_day.append(loss_profit)
        # --- Balance ----
        day_sum = sum_profit + commission_day + loss_profit
        balance_per_day.append(day_sum)
        # --- Sum Profit & Amount ---
        wallet.append(depo_sum + sum(balance_per_day) + sum(swap_day))
    lists = list(zip(format_days, profit_per_day, loss_per_day,
            balance_per_day, wallet))
    dicts = dict(zip(url_statements, lists))
    context = {'dicts': dicts,
               'profit_sum': round(profit_sum, 2),
               'loss_sum': round(loss_sum, 2),
               'ballance_sum': round(ballance_sum, 2),
               'commission_sum': round(commission_sum, 2),
               'swap_sum': round(swap_sum, 2)}
    return context


def f_stats(url_statement):
    df = df_db()
    day_st = df[df['close_time'].dt.strftime('%Y-%m-%d') == url_statement]
    df = df.drop(['id', 'ticket', 'taxes'], axis=1)
    day_st = day_st.drop(['id', 'taxes'], axis=1)
    day_real = datetime.strptime(url_statement, '%Y-%m-%d')
    format_day = day_real.strftime('%A - %d %B %Y')
    format_day_from_request = day_st
    # --- commision ---
    commission_sum = day_st.commission.sum()
    # --- Profit ----
    sum_profit = 0
    for i in day_st.profit:
        if i > 0:
            sum_profit += i
    sum_profit += commission_sum
    # --- Loss ---
    loss_profit = 0
    for i in day_st.profit:
        if i < 0:
            loss_profit += i
    # --- Balance ---
    day_sum = sum_profit + loss_profit
    # --- pkt ---
    pkt_buy, pkt_sell = 0, 0
    for index, row in day_st.iterrows():
        if row['type_st'] == 'buy':
            pkt_buy += (row['close_price'] - row['open_price'])
        elif row['type_st'] == 'sell':
            pkt_sell += (row['open_price'] - row['close_price'])
    pkt_sum = pkt_buy + pkt_sell
    # --- Swap ---
    swap_sum = day_st.swap.sum()
    # -------------------
    day_st['open_time'] = pd.to_datetime(day_st['open_time']).dt.date
    day_st['close_time'] = pd.to_datetime(day_st['close_time']).dt.date
    # --- Data to chart ---
    day_ste = df[df['close_time'].dt.strftime('%Y-%m-%d') == url_statement]
    chartx = list(day_ste.index.values)
    charty = list(day_ste.profit)
    day_st.rename(columns={
        'ticket': 'Ticket',
        'open_time': 'Open Time',
        'type_st': 'Type',
        'size_st': 'Size',
        'item_st': 'Item',
        'open_price': 'Open Price',
        's_l': 'Stop Loss',
        't_p': 'Take Profit',
        'close_time': 'Close Time',
        'close_price': 'Close Price',
        'commission': 'Commission',
        'taxes': 'Taxes',
        'swap': 'Swap',
        'profit': 'Profit'
        }, inplace=True)
    context = {
            'format_day': format_day, 'chartx': chartx, 'charty': charty,
            'day_sum': round(day_sum, 2), 'sum_profit': round(sum_profit, 2),
            'loss_profit': round(loss_profit, 2), 'pkt_sum': round(pkt_sum, 2),
            'commission_sum': round(commission_sum, 2), 'day_st': day_st,
            'swap_sum': round(swap_sum, 2), 'url_statement': url_statement,
            }
    return context


@login_required
def index(request):
    df = df_db()
    deposit = deposit_sum()
    withdrawal = withdrawal_sum()
    wallet_all = wallet()
    days = days_count()
    trade_count = transactions()
    # --- data to chart ---
    df['close_time'] = pd.to_datetime(df['close_time']).dt.date
    url_statements = list(set(df['close_time']))
    url_statements.sort()
    labels, chartdata = [], []
    day_profit, label_id = 0, 0
    for url_stat in url_statements:
        day_st = df.loc[df['close_time'] == url_stat]
        commission_day = day_st.commission.sum()
        swap_day = day_st.swap.sum()
        sum_profit = 0
        for i in day_st.profit:
            if i > 0:
                sum_profit += i
        loss_profit = 0
        for i in day_st.profit:
            if i < 0:
                loss_profit += i
        day_sum = sum_profit + commission_day + loss_profit
        day_profit += day_sum + swap_day
        label_id += 1
        labels.append(label_id)
        chartdata.append(deposit + day_profit)
    # -------------------------
    context = {'deposit': deposit, 'withdrawal': withdrawal,
               'wallet_all': wallet_all, 'days': days, 'labels': labels,
               'chartdata': chartdata, 'trade_count': trade_count}
    return render(request, 'cfd/index.html', context)


@login_required
def deposit(request):
    depo = depo_db()
    sum = deposit_sum()
    context = {'depo': depo, 'sum': sum}
    return render(request, 'cfd/deposit.html', context)


@login_required
def new_deposit(request):
    if request.method != 'POST':    # if 'GET'
        form = DepositForm()
    else:
        form = DepositForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('cfd:deposit')
    context = {'form': form}
    return render(request, 'cfd/new_deposit.html', context)


@login_required
def update_deposit(request, deposit_id):
    updepo = Deposit.objects.get(id=deposit_id)
    if request.method != 'POST':
        form = DepositForm(instance=updepo)
    else:
        form = DepositForm(instance=updepo, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('cfd:deposit')
    context = {'updepo': updepo, 'form': form}
    return render(request, 'cfd/update_deposit.html', context)


@login_required
def delete_deposit(request, deposit_id):
    depo = depo_db()
    try:
        deldepo = Deposit.objects.get(id=deposit_id)
    except Deposit.DoesNotExist:
        return redirect('cfd:deposit')
    deldepo.delete()
    context = {'depo': depo}
    return HttpResponseRedirect(reverse('cfd:deposit'))
    return render(request, 'cfd/deposit.html', context)


@login_required
def withdrawal(request):
    wdd = wd_db()
    sum = withdrawal_sum()
    context = {'wdd': wdd, 'sum': sum}
    return render(request, 'cfd/withdrawal.html', context)


@login_required
def new_withdrawal(request):
    if request.method != 'POST':    # if 'GET'
        form = WithdrawalForm()
    else:
        form = WithdrawalForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('cfd:withdrawal')
    context = {'form': form}
    return render(request, 'cfd/new_withdrawal.html', context)

django/04_statement/ver_1.2/cfd/templates/cfd/base.html
{% load bootstrap4 %}
{% load static %}

<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Statement</title>
	<link rel="icon" type="image/png" sizes="96x96"
	  href="{% static 'cfd/assets/logo_nook.png' %}">
	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}
	<link rel="stylesheet" 
	  href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
	<link rel="stylesheet" href="{% static 'cfd/style/style.css' %}">
{% block link %}{% endblock link %}
  </head>

  <body>
	<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
	  <div class="container-fluid">
		<a class="navbar-brand" href="{% url 'cfd:index' %}">
			<img src="{% static 'cfd/assets/logo_nook.png' %}" alt="" 
			width="30" height="24" class="d-inline-block align-text-top">
			Statement
		</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
			data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" 
			aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
		  <ul class="navbar-nav mr-auto">
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'cfd:deposit' %}">Deposit</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'cfd:withdrawal' %}">Withdrawal</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'cfd:statement' %}">Statement</a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'cfd:quarter' %}">Quarter</a>
			</li>

			<li class="nav-item dropdown">
			  <a class="nav-link dropdown-toggle" href="#"
				  id="navbarDropdown" role="button" data-bs-toggle="dropdown"
				  aria-expanded="false">
				Calculator
			  </a>
			  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
				  <li><a class="dropdown-item" href="{% url 'cfd:strategy' %}">Strategy</a></li>
				  <li><a class="dropdown-item" href="{% url 'cfd:calc' %}">Take Profit</a></li>
				  <li><a class="dropdown-item" href="{% url 'cfd:pipmargin' %}">Margin & Pip Value</a></li>
				  <li><a class="dropdown-item" href="{% url 'cfd:daily' %}">Daily Calculations</a></li>
				<li><a class="dropdown-item" href="{% url 'cfd:point' %}">Daily Point</a></li>
			  </ul>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'cfd:year' %}">Year</a>
			</li>
		  </ul>

		  <ul class="navbar-nav ml-auto">
			{% if user.is_authenticated %}
			<li class="nav-item">
				<span class="navbar-text">Hello, {{ user.username }}.</span>
			</li>  
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
			</li>  
			{% else %}
			<li class="nav-item">
			  <form>
				<button type="submit" formaction="{% url 'users:login' %}" 
				  class="btn btn-outline-success btn-sm">Login</button>
				<button type="submit" formaction="{% url 'users:register' %}" 
				  class="btn btn-outline-success btn-sm">Register</button>
			  </form>
			</li>  
			{% endif %}
		  </ul>

		</div>
	  </div>
	</nav>
{% block content %}{% endblock content %}
	<!-- Bootstrap Date-Picker Plugin -->
	<script 
	src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" 
	integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" 
	crossorigin="anonymous">
	</script>
	<script type="text/javascript" 
	src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js">
	</script>
	<link rel="stylesheet" 
	href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
  </body>
</html>

django/04_statement/ver_1.2/cfd/templates/cfd/footer.html
{% load static %}
{% block link %}
	<link rel="stylesheet" href="{% static 'cfd/style/footer.css' %}" type="text/css">
{% endblock link %}
	<footer class="footer mt-auto py-3 ">
	  <div class="container">
		<ul class="nav justify-content-center border-bottom ">
		  <li class="nav-item">
			  <a href="{% url 'cfd:index' %}" class="nav-link px-2 text-muted">
				  Home
			  </a>
		  </li>
		  <li class="nav-item">
			  <a href="{% url 'cfd:deposit' %}" class="nav-link px-2 text-muted">
				  Deposit
			  </a>
		  </li>
		  <li class="nav-item">
			  <a href="{% url 'cfd:withdrawal' %}" class="nav-link px-2 text-muted">
				  Withdrawal
			  </a>
		  </li>
		  <li class="nav-item">
			  <a href="{% url 'cfd:statement' %}" class="nav-link px-2 text-muted">
				  Statement
			  </a>
		  </li>
		  <li class="nav-item">
			  <a href="{% url 'cfd:quarter' %}" class="nav-link px-3 text-muted">
				  Quarter
			  </a>
		  </li>
		  <li class="nav-item dropup">
		    <a class="nav-link dropdown-toggle text-muted" href="#"
				data-bs-toggle="dropdown" aria-expanded="false">Calculator</a>
			<ul class="dropdown-menu" aria-labelledby="dropdown10">
			  <li><a class="dropdown-item" href="{% url 'cfd:calc' %}">
					  Take Profit</a></li>
			  <li><a class="dropdown-item" href="{% url 'cfd:pipmargin' %}">
					  Margin & Pip Value</a></li>
			  <li><a class="dropdown-item" href="{% url 'cfd:daily' %}">
					  Daily Calculations</a></li>
			  <li><a class="dropdown-item" href="{% url 'cfd:point' %}">
					  Daily Point</a></li>
			</ul>
		  </li>
		  <li class="nav-item">
			  <a href="{% url 'cfd:year' %}" class="nav-link px-2 text-muted">
				  Year
			  </a>
		  </li>
		  <li class="nav-item">
<!--			  <a href="https://s171.cyber-folks.pl/phpmyadmin/"-->
			  <a href="http://localhost/phpmyadmin/"
				  target="_blank" class="nav-link px-2 text-muted">
				  phpMyAdmin
			  </a>
		  </li>
		  <li class="nav-item">
			  <a href="https://getbootstrap.com/docs/"
				  target="_blank" class="nav-link px-2 text-muted">
				  Bootstrap
			  </a>
		  </li>
		  <li class="nav-item">
			  <a href="https://docs.djangoproject.com/"
				  target="_blank" class="nav-link px-2 text-muted">
				  Django
			  </a>
		  </li>
		  <li class="nav-item">
			<a href="#" data-bs-toggle="modal" data-bs-target="#Modal"
				class="nav-link px-2 text-muted">About</a>
		  </li>
		</ul>
		<p class="text-center text-muted">&copy; 2023 - Nook Web Developer</p>
	  </div>
	</footer>

<!-- Modal -->
<div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="ModalLabel" 
	aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="nmodal-content shadow mb-5 bg-body rounded">
      <div class="nmodal-header">
		<img class="nookico" alt="nook icon" 
		  src="{% static 'cfd/assets/logo_nook.png' %}">
		  <div class="ml-3">
			<h4 class="modal-title" id="ModalLabel">Statement</h4>
			<p class="">Version 1.2 - february 2023</p>
		  </div>
      </div>
      <div class="modal-body">
		<div class="panel-group" id="accordion" role="tablist"
			aria-multiselectable="true">
		<p class="lead">Release:</p>

		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="headingOne">
			  <h5 class="panel-title">
				<a role="button" data-toggle="collapse" class="nlink" 
					data-parent="#accordion" href="#collapseOne" 
					aria-expanded="true" aria-controls="collapseOne">
				  Version 1.0
				</a>
			  </h5>
			</div>
			<div id="collapseOne" class="panel-collapse collapse in" 
				role="tabpanel" aria-labelledby="headingOne">
			  <div class="panel-body">
				The basic functionality of the 'Statement Application' deploy to the production server 
			  </div>
			</div>
		  </div> <!-- Panel -->

		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="headingTwo">
			  <h5 class="panel-title">
				<a class="collapsed nlink" role="button" data-toggle="collapse"
					data-parent="#accordion" href="#collapseTwo" 
					aria-expanded="false" aria-controls="collapseTwo">
					Version 1.1
				</a>
			  </h5>
			</div>
			<div id="collapseTwo" class="panel-collapse collapse" 
				role="tabpanel"	aria-labelledby="headingTwo">
			  <div class="panel-body">
				Major changes:
				<ul>
					<li>added second chart 'return by trade' on index site</li>
					<li>highlighted all trades finished 'take profit' or 'stop loss'</li>
					<li>possibility to delete the single statement from the database</li>
					<li>added site about in modal window</li>
					<li>The ability to upload a statement of files to databases</li>
				</ul>
			  </div>
			</div>
		  </div> <!-- Panel -->

		  <div class="panel panel-default">
			<div class="panel-heading" role="tab" id="headingThree">
			  <h5 class="panel-title">
				<a class="collapsed nlink" role="button" data-toggle="collapse"
					data-parent="#accordion" href="#collapseThree"
					aria-expanded="false" aria-controls="collapseThree">
					Version 1.2
				</a>
			  </h5>
			</div>
			<div id="collapseThree" class="panel-collapse collapse"
				role="tabpanel"	aria-labelledby="headingThree">
			  <div class="panel-body">
				Major changes:
				<ul>
					<li>added strategy section</li>
				</ul>
			  </div>
			</div>
		  </div> <!-- Panel -->

		</div> <!-- accordion -->
	  </div> <!-- modal-body -->
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary btn-sm" 
			data-bs-dismiss="modal">Close
		</button>
	  </div> <!-- modal-footer -->
    </div>
  </div>
</div>

django/04_statement/ver_1.2/cfd/templates/cfd/new_deposit.html
{% extends "cfd/base.html" %}
{% block content %}
	<main class="container flex-shrink-0">
	  <div class="p-5 rounded">
		<p class="lead">Deposit</p>
		<div class="row">
			<div class="col-md-6">
				<div class="container bootstrap-iso">
					<form action="{% url 'cfd:new_deposit' %}" method="post">
						{% csrf_token %}
						  <div class="col-auto">
							<label class="visually-hidden" 
								for="autoSizingInput">Date
							</label>
							<input type="text" name="date_dep" class="form-control" 
							  id="date" placeholder="2021-01-25">
						  </div>
						  <div class="col-auto mt-3">
							<label class="visually-hidden" 
								for="autoSizingInputGroup">Amount
							</label>
							<div class="input-group">
							  <input type="number" name="amount_dep"
									 			 class="form-control"
												 id="autoSizingInputGroup"
												 placeholder="1500">
							</div>
						  </div>
						  <div class="col-auto mt-3">
							<label class="visually-hidden"
								for="autoSizingSelect">Bank:  
							</label>
							<select class="form-select" type="text" 
								name="bank_name" id="autoSizingSelect">
							  <option selected>iPKO</option>
							  <option value="Pekao">Pekao</option>
							</select>
						  </div>
						  <div class="col-auto text-center">
							<button type="submit" 
								class="btn btn-outline-dark btn-sm">Send
							</button>
						  </div>					
					</form>
				</div>
			</div>
			<div class="col-md-6">
			</div>
		</div>
	  </div>
	</main>
<script>
    $(document).ready(function(){
      var date_input=$('input[name="date_dep"]'); //our date input has the name "date"
      var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
      var options={
        format: 'yyyy-mm-dd',
        container: container,
        todayHighlight: true,
        autoclose: true,
      };
      date_input.datepicker(options);
    })
</script>
	{% include "cfd/footer.html" %}
{% endblock content %}